[package]
name = "ray"
version = "0.1.0"
authors = ["manuel_deval <manuel.deval@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
typetag="0.1"
math = { path = "../math" }

[lib]
path="src/lib.rs"